ami-iit/rod

src/rod/sdf.py

The simulator could be installed either following the [official instructions](https://gazebosim.org/docs/garden/install) of from [conda-forge](https://github.com/conda-forge/libignition-gazebo-feedstock).

Add optional URDF support if Gazebo Sim or Ignition Gazebo are found

---

src/rod/link.py
src/rod/model.py
src/rod/sdf.py

There are a bunch of elements that could be parsed either as single objects or lists. This complicates downstream logic since an instance check should be performed. This PR adds new helpers that always return a list even in case of single objects.

Add helper methods to access resources that could be lists

---

setup.cfg
src/rod/common.py
src/rod/link.py
src/rod/model.py

- Enable to build `Pose` from homogeneous matrix ([ref](http://sdformat.org/tutorials?tut=specify_pose))
- Return homogeneous matrix from `Pose` ([ref](http://sdformat.org/tutorials?tut=specify_pose))
- Return 3D inertia tensor from `Inertial`
- Return if a model is fixed-base or floating-base
- Return the canonical link ([ref](http://sdformat.org/tutorials?tut=pose_frame_semantics#nested-canonical-links))

Add high-level helper methods

---

setup.cfg
src/rod/kinematics/__init__.py
src/rod/kinematics/kinematic_tree.py
src/rod/kinematics/tree_transforms.py
src/rod/model.py
src/rod/tree/__init__.py
src/rod/tree/directed_tree.py
src/rod/tree/tree_elements.py
src/rod/utils/frame_convention.py
src/rod/utils/resolve_frames.py

This PR introduces a number of new features, all targeted to be used as utilities for processing a `rod.Model` as a tree. Some of the feature below or future features are taken from [`jaxsim.parsers`](https://github.com/ami-iit/jaxsim/tree/f088a1dcadd142844a812595149c877e604057b2/src/jaxsim/parsers), that could be replaced in the future by these new `rod` features.
Although SDFormat supports closed kinematic loops / parallel robots ([example](url)), `rod` currently doesn't, as by the way also URDF. Excluding these particular families of kinematics, any robot model could be modelled as a _directed tree_ (i.e. an oriented Direct Acyclic Graph with nodes restricted to have just one parent).
In our directed tree:
- Links are the nodes
- Joints are the edges
Furthermore, in order to support …

Add utilities to handle SDF models as a directed trees

---

README.md
src/rod/urdf/exporter.py
src/rod/utils/frame_convention.py
src/rod/utils/resolve_frames.py

This PR implements the SDF -> URDF conversion by exporting the in-memory model to URDF. Closes #6.
- Links and joints are converted directly to URDF exploiting the already existing `FrameConvention.Urdf` that expresses the poses of a model compatibly with URDF[^1]
- Frames are converted to (fixed_joint->fake_link) pairs and attached to the first suitable frame parent
- Gazebo elements are included for preventing lumping frames in case the exported URDF is converted back to SDF[^2]
- The URDF exporter accepts a list of fixed joints to keep for the same reason, and the proper Gazebo elements are included in the resulting URDF
- Not all SDF features can be converted to URDF, e.g. links must have a trivial pose w.r.t. their parent joint
- The root of the URDF model is the canonical link, …

Exporting to URDF

---

src/rod/sdf/model.py
src/rod/utils/resolve_uris.py

This is an initial implementation of resolving local URIs of the form e.g. `<something>://dir/file.stl` where `<something>` is part of `IGN_GAZEBO_RESOURCE_PATH`.
After parsing a URDF/SDF model, calling `Model.resolve_uris()` will replace all the URIs with the real path to the local file.
Partially resolves #8.

Resolve URIs to mesh files

---

src/rod/builder/primitive_builder.py
src/rod/builder/primitives.py
src/rod/sdf/link.py
src/rod/sdf/model.py

Initial support of creating elements of primitive shapes.
Quick example:
```python
import numpy as np
import rod
from rod.builder import primitives
link_H_com = np.eye(4)
link_H_com[0:3, 3] = np.array([0, 0, 1.0])
model = (
primitives.SphereBuilder(name="sphere", mass=1.0, radius=0.1)
.build_model()
.add_link()
.add_inertial(pose=rod.Pose.from_transform(transform=link_H_com))
.add_visual()
.build()
)
sdf = rod.Sdf(version="1.9", model=model)
print(sdf.serialize(pretty=True))
sdf_string = sdf.serialize(pretty=True)
```

Add utilities to build primitive shapes

---

.github/workflows/ci_cd.yml

This should permit us to quickly realize if a dependency is breaking the library, so that we can easily understand which change caused the problem.

Add nightly job

---

.github/workflows/ci_cd.yml
setup.cfg
tests/test_urdf_parsing.py
tests/utils_models.py

This PR adds a first test in which `rod` is used to load URDF models from [robot-descriptions/robot_descriptions.py](https://github.com/robot-descriptions/robot_descriptions.py) and check the read information against [robotology/idyntree](https://github.com/robotology/idyntree/).
Note that `rod` has not direct support of URDF, we only support SDF. As a workaround, we expect to find `ign sdf|gz sdf` installed system-wise, and call `sdformat` to convert the URDF to SDF before parsing it with `rod`.
This processing has some side effect. In particular, the URDF model is processed by sdformat and the resulting SDF might differ particularly regarding the lumping logic of links attached through fixed joints.
The test uses iDynTree as ground truth. Similarly, also iDynTree performs link lumping, …

Add Continuous Integration test on parsing URDF models

---

src/rod/builder/primitive_builder.py
src/rod/pretty_printer.py
src/rod/urdf/exporter.py

We use the [`//visual/material/diffuse`](http://sdformat.org/spec?ver=1.11&elem=material#material_diffuse) SDF element and convert it into the [`visual/material/color@rgba`](http://wiki.ros.org/urdf/XML/link#Elements) URDF attribute.
Note that other material properties of SDF are ignored. We cannot work around it since the material properties of URDF are more limited than those of SDF.
Additional information on SDF materials:
- http://sdformat.org/tutorials?tut=spec_materials

Add support of colors when exporting to URDF geometries with material element

---

.github/workflows/ci_cd.yml

For reason that I don't understand it no longer gets triggered. @traversaro any clue?
Furthermore:
- Add in CI new `resolve-robotics-uri-py` dependency that was missing in #28. I didn't notice it because the CI/CD didn't start.
- Add `workflow_dispatch`.

Update CI/CD workflow

---

.github/workflows/ci_cd.yml
setup.cfg
src/rod/builder/primitives.py
tests/test_meshbuilder.py

This pull requests adds the possibility to build meshes by using [trimesh](https://github.com/mikedh/trimesh).
It implements a `MeshBuilder` class which implements the calculation for the mesh's moment of inertia and its geometry.
Summary of changes:
- Implement MeshBuilder object and override its `inertia` and `geometry` methods with a calculation using `trimesh` methods.
- Implement tests on mesh-building.

Add support for meshes to primitive builders

---

.github/workflows/ci_cd.yml
src/rod/__init__.py
src/rod/kinematics/tree_transforms.py
src/rod/sdf/model.py
src/rod/urdf/exporter.py
src/rod/utils/frame_convention.py
src/rod/utils/gazebo.py
src/rod/utils/resolve_frames.py
tests/test_urdf_exporter.py

This PR:
- Fixes the computation of the `//frame/pose` element when not explicitly defined in the model description following the [documented semantics](http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#frame) (pay attention how the pose is defined when there is no explicit `//frame/pose`, and what's the default when also `//frame/attached_to` is not defined).
- Enhances the process of converting ` //frame` elements to compatible chains in URDF.
---
In the last two year, `sdformat` received different updates on how URDF models are converted to SDF. In particular, few of them altered how kinematic chains involving massless links (or with tiny masses) are processed. Here below some references for those that want to dig deeper:
- …

Enhance processing and URDF export of `//frame` elements

---

src/rod/__init__.py
src/rod/builder/primitive_builder.py
src/rod/builder/primitives.py
src/rod/kinematics/kinematic_tree.py
src/rod/kinematics/tree_transforms.py
src/rod/logging.py
src/rod/pretty_printer.py
src/rod/sdf/element.py
src/rod/sdf/link.py
src/rod/sdf/model.py
src/rod/sdf/sdf.py
src/rod/sdf/world.py
src/rod/tree/directed_tree.py
src/rod/tree/tree_elements.py
src/rod/urdf/exporter.py
src/rod/utils/frame_convention.py
src/rod/utils/gazebo.py
src/rod/utils/resolve_frames.py
src/rod/utils/resolve_uris.py
tests/utils_models.py

This pull request includes several code improvements and bug fixes. Here is a summary of the changes:
- Use structural pattern matching (NOTE: This requires Python>=3.10, so I can eventually drop this)
- Use `utf-8` encoding when reading from files (Avoids file read error in Windows)
- Cache tree transforms
- Cache gazebo executable path
- General exceptions improvements
- General typing improvements
```python
%timeit _ = rod.Sdf.load(sdf=urdf_path, is_urdf=True)
```
```diff
< 683 ms ± 24.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 434 ms ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
```python
%timeit sdf.model.switch_frame_convention(frame_convention=rod.FrameConvention.Urdf)
```
```diff
< 511 ms ± 8.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop …
```

Improve model handling speed

---

src/rod/builder/primitives.py
tests/test_meshbuilder.py

With this pull request, I suggest to move the mesh loading part inside of a context manager to ensure that the file is properly closed, but most importantly to avoid a bug from trimesh where a string can be passed to `trimesh.load_mesh`, but internally it requires a file-like object. This way, the mesh is instantly loaded using a file object.
Also, I added a logging warning from `MeshBuilder` when an empty mesh is loaded.

Improved meshbuilder's mesh handling

---

src/rod/sdf/geometry.py
src/rod/tree/tree_elements.py
src/rod/urdf/exporter.py

I realized that the CI pipeline got disabled automatically due to inactivity, and the last PRs have not been tested. Unfortunately, @flferretti and me merged things only compatible with Python >= 3.12.
This PR restores the support of older Python version.

Fix project for Python < 3.12

---

src/rod/sdf/sdf.py
tests/test_urdf_exporter.py
tests/test_urdf_parsing.py

This PR enable detecting the XML type from the parsed string.

Automatically detect `sdf` extension from parsed string

---

.github/workflows/ci_cd.yml

Overnight, GitHub Actions updated the default `ubuntu-latest` to `ubuntu-22.04`. It's not a big deal for this project, but the OSRF repository does not longer ships `libsdformat13`.
Since this is the oldest version we want to support, it makes sense to keep testing our code against it. In this PR, I pin `ubuntu-22.04` in the runner so that we keep using `libsdformat13`.

Pin Ubuntu Jammy in CI/CD

---

.github/workflows/ci_cd.yml

Similar to https://github.com/ami-iit/jaxsim/pull/174 . I added the `ci_cd.yml` action as Trusted Publisher on PyPI side, so I think we can then merge this PR and remove the `PYPI_TOKEN` from the repo secrets (that I guess is @diegoferigo's one).

Update CI/CD workflow to interface with PyPI as Trusted Publisher

---

src/rod/builder/primitive_builder.py
src/rod/builder/primitives.py
src/rod/sdf/link.py
tests/test_meshbuilder.py

This PR enhances the mesh support introduced in #33. In particular:
- The path to the mesh can now be an URI. Storing the URI instead of the absolute path is important if the builder is used to create a model programmatically that can be used on different machines. Now the URI is resolved only when the trimesh object is created, but it's stored as unresolved so that it can be serialized in a SDF/URDF model as URI.
- Allows to pass the mass and inertia tensor to the builder. This information stored in mesh files is not always what's used for the inertial properties, and not always valid.
cc @lorycontixd can you please try if the changes break your pipeline? For sure you have to update `mesh_path` with `mesh_uri`. Sorry for this change, I overlooked this use-case in your original …

Update `MeshBuilder` class

---

.github/workflows/style.yml

This PR fixes the usage of `--color` after https://github.com/isort/isort-action/pull/96 updated the isort action to run in a virtual environment.

Workaround to fix new isort action

---

src/rod/sdf/sdf.py
tests/test_urdf_parsing.py

The non-existing paths will be handled by `pathlib.Path.read_text()`, eventually raising a `FileNotFoundError`.

Refactor SDF handling logic for non-existing string paths

---

src/rod/utils/gazebo.py

Redirecting `stderr` to a pipe allows for better error handling and separation of standard output and error messages.
Fixes #52

Redirect `stderr` to pipe instead of STDOUT

---

.gitattributes
.gitignore
README.md
pixi.lock
pyproject.toml

This PR introduces support for Pixi by updating the `.gitignore`, adding dependencies in `pyproject.toml`, and configuring LFS for `pixi.lock`, including a test task for Pixi environments.

Add Pixi support and configuration files

---

src/rod/sdf/element.py

This pull request includes a minor change to the `serialize_float` method in the `src/rod/sdf/element.py` file. The change ensures that if the input data is an integer, it is converted to a float before being serialized.
* [`src/rod/sdf/element.py`](diffhunk://#diff-37340470d066c0eeb2f42fb1bd407f15d354c70e790f613000f0a0302774610dR44-R45): Added a check to convert integer input to float in the `serialize_float` method.

Cast `int` values to `float` when required

---

src/rod/utils/resolve_frames.py

This pull request adds a validation of the `default_relative_to` parameter.
* [`src/rod/utils/resolve_frames.py`](diffhunk://#diff-b4dfbc45c918739b288531a69cce94b42cbafa9117eeb0ab3d1c974bbdf641dbL19-R22): Modified the `update_element_with_pose` function to validate that `default_relative_to` is either a string or a list of strings. If it is a string, it is converted to a list. If it is not a string or a list of strings, a `TypeError` is raised.
This prevents cases in which the second argument of `rod.Pose` is passed as RPY coordinates, which made `relative_to` a list of floats.
```python
inspect.signature(rod.Pose)
rod.Pose([0.2, 0, base_height / 2], [0, 0, 0])
```
C.C. @xela-95

Add typechecking on `relative_to` argument of `rod.Pose`

---

.github/release.yml

This pull request includes a small change to the `.github/release.yml` file. The change excludes bot authors from the changelog to keep it clean and relevant.
* [`.github/release.yml`](diffhunk://#diff-409fea45635f464aa0592700a92cf483be2f5b21b60f8f1b383756067ee79213R1-R5): Added configuration to exclude authors `dependabot` and `pre-commit-ci` from the changelog.

Filter out bot-authored commits from generated release notes
